import {Poppins, PT_Serif, Karla} from 'next/font/google'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal"],
  variable: '--font-poppins',
  subsets: ["latin"]
})
const ptserif = PT_Serif({
  weight: ["400", "700"],
  style: ["normal"],
  variable: '--font-ptserif',
  subsets: ["latin"]
})
const karla = Karla({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  style: ["normal"],
  variable: '--font-karla',
  subsets: ["latin"]
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${ptserif.variable} ${karla.variable}`}>{children}</body>
    </html>
  )
}
